### PR TITLE
Added more improvements about this plone theme package

### PR DESCRIPTION
**Pull request by macagua**
@giacomos can you check these improvements and if all are Ok, can merged it?

### CODE REVIEW

**Comment by giacomos** [comment]
Hi Leonardo,
     I do not work for this company anymore so unfortunately I cannot merge your PR.

Maybe @davidemoro or @realefab ?
Cheers

**Comment by macagua** [comment]
@giacomos thanks for you response :+1: 

Maybe @davidemoro or @realefab can check these improvements and if all are Ok, can merged it?

**Comment by realefab** [comment]
Hi all,
@giacomos, it's a pleasure to read you again.

Leonardo, can you give me your gihub id, I'll add you to the repo.

Thanks,
Fabrizio

Il giorno ven 22 giu 2018 alle ore 19:16 Leonardo J. Caballero G. <
notifications@github.com> ha scritto:

**Comment by macagua** [comment]
Hi all

@realefab my gihub id is macagua

Thanks you!

**Comment by realefab** [comment]
You got push rights.

Thanks,
Fabrizio

Il giorno lun 25 giu 2018 alle ore 15:34 Leonardo J. Caballero G. <
notifications@github.com> ha scritto:

**Comment by macagua** [comment]
@realefab thanks you! :+1:

**Comment by macagua** [comment]
@realefab then just, I make a "git push" directly to "master" branch and close and comment this "pull request" right?

**Comment by macagua** [comment]
@realefab Sorry, I haven't seen see the notification that you send me for this package!

Then, it was done it!

Thanks!

**Comment by realefab** [comment]
You are welcome.

Thanks,
Fabrizio

Il giorno mer 27 giu 2018 alle ore 22:39 Leonardo J. Caballero G. <
notifications@github.com> ha scritto:

**Pull request merged**
